# Generated by Django 5.0.2 on 2024-08-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogdashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='max_length = 60')),
                ('blog', models.TextField(verbose_name='max_length = 120')),
                ('myimg', models.ImageField(blank=True, null=True, upload_to='userprofilr')),
            ],
        ),
    ]
